version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: echo "This is the build job"
  test:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: echo "This is the test job"
      - run: sleep 5
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test